= 创建 Windows 虚拟机

== virtio-win

* Windows 默认不识别 KVM 的 virtio 磁盘（virtio-blk）和网卡（virtio-net）。
* 如果你使用默认磁盘/网络模型（如 IDE + rtl8139），性能极差且无法发挥 KVM 优势。
* 必须提供 VirtIO 驱动 ISO，并在安装过程中加载。
* 官方下载查找地址: <https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/>
* 官方最新稳定版下载地址: <https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso>
* 官方最新版下载地址: <https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso>

== 创建命令

[source,bash]
----
# Win7
virt-install \
    --name win7 --os-variant win7 \
    --vcpus=4,maxvcpus=8 \
    --memory=8192,maxmemory=16384 \
    --cdrom ~/kvm/iso/cn_windows_7_professional_with_sp1_x64_dvd_u_677031.iso \
    --disk path=~/opt/kvm/data/Win7.qcow2,format=qcow2,size=50,bus=virtio,cache=writethrough,io=threads,discard=unmap \
    --disk path=~/opt/kvm/iso/virtio-win-0.1.285.iso,device=cdrom,readonly=yes \
    --graphics vnc,listen=0.0.0.0,port=5900,password=******** \
    --network bridge=br0,model=e1000e \
    --controller usb,model=ich9-ehci1 \
    --virt-type=kvm \
    --cpu host-model,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time

# Win10
virt-install \
    --name win10 --os-variant win10 \
    --vcpus=4,sockets=2,cores=1,threads=2 \
    --memory=16384,maxmemory=24576 \
    --cdrom ~/opt/kvm/iso/cn_windows_10_business_editions_version_1909_x64_dvd_0ca83907.iso \
    --disk path=~/opt/kvm/data/win10-c.raw,format=raw,size=38,bus=virtio,cache=none,io=native \
    --disk path=~/opt/kvm/iso/virtio-win-0.1.285.iso,device=cdrom,readonly=yes \
    --graphics vnc,listen=0.0.0.0,port=5901,password=******** \
    --network bridge=br0,model=virtio \
    --virt-type=kvm \
    --cpu host-passthrough \
    --features hyperv_relaxed=on,hyperv_spinlocks=on,hyperv_vapic=on \
    --clock offset=localtime,hypervclock_present=yes \
    --noautoconsole
----

参数说明：

* --name: 虚拟机名称
* --os-variant: 指定操作系统类型和版本
* --vcpus: CPU核心数 vcpus = sockets * cores * threads
* --memory: 分配的内存大小
* --cdrom: Windows安装介质路径
* --disk: 虚拟硬盘路径和大小
** discard=unmap: 本质是让虚拟机把「不再使用的空闲块」通知给宿主机块设备，让它回收空间。对于 SSD/NVMe 等支持 TRIM 的设备启作用，机械硬盘不启作用。
* --graphics: 使用VNC或SPICE进行图形化管理
** password: VNC密码，不能超过8位数
* --network: 虚拟机网络配置
* --cpu host-passthrough: 直接将宿主机 CPU 的型号、功能标志（flags）全部暴露给 VM，相当于“让 VM 看到和物理机一模一样的 CPU”
* --features hyperv_*：提升 Windows 性能
* --clock: 设置时钟同步
* --noautoconsole: 不自动打开控制台(VNC窗口)

== VNC客户端连接

[source,bash]
----
vncviewer xxx.xxx.xxx.xxx:5900
----

== 开启 Windows 远程桌面

* Win7
+
计算机 -> 属性 -> 远程设置 -> 远程 -> 允许运行任意版本远程桌面的计算机连接(较不安全)(L)
* Win10
+
此电脑 -> 属性 -> 远程设置 -> 远程 -> 允许远程连接到此计算机(L)