= frp
:scripts: cjk
:toc:
:toc-title: 目录
:toclevels: 4

== frp 简介
=== 文档
https://gofrp.org/docs/overview/

=== frp 是什么？
frp 是一个专注于内网穿透的高性能的反向代理应用，支持 TCP、UDP、HTTP、HTTPS 等多种协议。可以将内网服务以安全、便捷的方式通过具有公网 IP 节点的中转暴露到公网。

=== 为什么使用 frp？
通过在具有公网 IP 的节点上部署 frp 服务端，可以轻松地将内网服务穿透到公网，同时提供诸多专业的功能特性，这包括：

. 客户端服务端通信支持 TCP、KCP 以及 Websocket 等多种协议。
. 采用 TCP 连接流式复用，在单个连接间承载更多请求，节省连接建立时间。
. 代理组间的负载均衡。
. 端口复用，多个服务通过同一个服务端端口暴露。
. 多个原生支持的客户端插件（静态文件查看，HTTP、SOCK5 代理等），便于独立使用 frp 客户端完成某些工作。
. 高度扩展性的服务端插件系统，方便结合自身需求进行功能扩展。
. 服务端和客户端 UI 页面。

== 下载
https://github.com/fatedier/frp/releases

== 解压
[,shell]
----
tar zxvf frp_0.47.0_linux_amd64.tar.gz
----

== 部署服务器
=== 上传
将解压后的以 `frps` 开头的系列文件上传到具有公网 IP 的机器上，建议放置到 `/usr/local/frp/` 目录中

=== 配置
./usr/local/frp/frps.ini
[,ini]
----
[common]
# 客户端连上来需要用到的令牌
token = ********

# 服务器监听端口(须保证打通防火墙，从互联网可以访问这个端口)
bind_port = 7000

# 下面三种udp传输类型同时只能启用一个
# xtcp用来打洞的监听端口(xtcp 绑定的是 udp 端口，可以和 bind_port 一样)
# bind_udp_port = 57000
# 服务器启用kcp(kcp 绑定的是 udp 端口，可以和 bind_port 一样)
# kcp_bind_port = 57000
# 服务器启用quic(quic 绑定的是 udp 端口，可以和 bind_port 一样)
quic_bind_port = 57000

# TLS加密(除了xtcp，否则与use_encryption加密重复了)
# frpc 校验 frps 身份
#tls_cert_file = /usr/local/frp/server.crt
#tls_key_file = /usr/local/frp/server.key
# frps 验证 frpc 的身份
#tls_trusted_ca_file = /usr/local/frp/ca.crt
# 不要求客户端必须用tls来连接(目前在设置tls_trusted_ca_file之后此项设置无效)
#tls_only = false

# 服务端管理界面
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = ********
----

=== 运行
==== 直接运行
[,shell]
----
./frps -c ./frps.ini
----

==== 后台运行
[,shell]
----
mkdir -p /var/log/frp
nohup /usr/local/frp/frps -c /usr/local/frp/frps.ini > /usr/local/frp/frps.log 2>&1 &
----

==== systemd方式
./etc/systemd/system/frps.service
[,ini]
----
[Unit]
# 服务名称，可自定义
Description = frp server
After = network.target syslog.target
Wants = network.target

[Service]
Type = simple
# 启动frps的命令，需修改为您的frps的安装路径
ExecStart = /usr/local/frp/frps -c /usr/local/frp/frps.ini

[Install]
WantedBy = multi-user.target
----

[,shell]
----
# 启动服务
systemctl start frps
# 停止服务
systemctl stop frps
# 重启服务
systemctl restart frps
# 查看服务状态
systemctl status frps
# 配置 frps 开机自启
systemctl enable frps
----

==== Supervisor方式
./etc/supervisord.conf
[,ini]
----
....

[include]
files = supervisord.d/*.ini
----

./etc/supervisord.d/frps.ini
[,ini]
----
[program:frps]
directory = /root/
command = /usr/local/frp/frps -c /usr/local/frp/frps.ini
autostart = true
startsecs = 10
autorestart = true
startretries = 100000
stdout_logfile = /usr/local/frp/frps.log
----

* supervisord 服务管理
[,shell]
----
# 重启服务
systemctl restart supervisord
# 查看服务启动状态
systemctl status supervisord
# 配置 supervisord 开机自启
systemctl enable supervisord
----

* supervisor 进程管理（监听/启动/停止/重启）
[,shell]
----
# 查看所有进程的状态
supervisorctl status
# 停止 frps
supervisorctl stop frps
# 启动 frps
supervisorctl start frps
# 重启 frps
supervisorctl restart frps
# 配置文件修改后可以使用该命令加载新的配置
supervisorctl update
# 重新启动配置中的所有程序
supervisorctl reload
----

== 部署客户端
=== 上传
将解压后的以 `frpc` 开头的系列文件上传到内网服务所在的机器上，建议放置到 `/usr/local/frp/` 目录中

=== 配置
./usr/local/frp/frpc.ini
[,ini]
----
[common]
# 客户端连接服务器需要用到的令牌
token = ********

# 客户端访问服务器的地址
server_addr = <服务器地址>
# 客户端访问服务器的端口
server_port = 7000

# 以下的kcp/quic只能同时启用一个，而且当只有两个都禁用时，才能使用xtcp
# 启用 kcp 协议(server_port 必须指定为 frps 的 kcp_bind_port)
# protocol = kcp
# 启用 QUIC 协议(server_port 必须指定为 frps 的 quic_bind_port)
protocol = quic

# 启用TLS加密，减少被嗅探的可能
tls_enable = true
disable_custom_tls_first_byte = true

# frps 验证 frpc 的身份
#tls_cert_file = /usr/local/frp/client.crt
#tls_key_file = /usr/local/frp/client.key
# frpc 校验 frps 身份
#tls_trusted_ca_file = /usr/local/frp/ca.crt

# 客户端管理界面
admin_addr = 127.0.0.1
admin_port = 7400
admin_user = admin
admin_pwd = ********

# 将客户端管理界面暴露到外网
[xxx_admin_ui]
type = tcp
# 对应客户端管理界面的端口
local_port = 7400
# 暴露出去的端口
remote_port = 7400
# 启用加密
use_encryption = true
# 启用压缩
use_compression = true

[xxx_ssh]
type = tcp
# 客户端本地开启ssh的端口号
local_port = 22
# 用户ssh通过服务器访问本机需要配置的端口
remote_port = 6000
# 启用加密
use_encryption = true
# 启用压缩
use_compression = true
----

=== 运行
==== 直接运行
[,shell]
----
./frpc -c ./frpc.ini
----

==== 后台运行
[,shell]
----
mkdir -p /var/log/frp
nohup /usr/local/frp/frpc -c /usr/local/frp/frpc.ini > /usr/local/frp/frpc.log 2>&1 &
----

==== systemd方式
./etc/systemd/system/frpc.service
[,ini]
----
[Unit]
# 服务名称，可自定义
Description = frp client
After = network.target syslog.target
Wants = network.target

[Service]
Type = simple
# 启动frpc的命令，需修改为您的frpc的安装路径
ExecStart = /usr/local/frp/frpc -c /usr/local/frp/frpc.ini

[Install]
WantedBy = multi-user.target
----
[,shell]
----
# 启动服务
systemctl start frpc
# 停止服务
systemctl stop frpc
# 重启服务
systemctl restart frpc
# 查看服务状态
systemctl status frpc
# 配置 frpc 开机自启
systemctl enable frpc
----

==== Supervisor方式
. 查看默认的配置文件 supervisord.conf
** linux
+
./etc/supervisord.conf
[,ini]
----
....

[include]
files = supervisord.d/*.ini
----

** mac
+
./usr/local/etc/supervisord.conf
[,ini]
----
....

[include]
files = /usr/local/etc/supervisor.d/*.ini
----

. 编辑进程的配置文件
+
** /etc/supervisord.d/frpc.ini(linux)
** /usr/local/etc/supervisor.d/frpc.ini(mac)
+
[,ini]
----
[program:frpc]
directory = /root/
command = /usr/local/frp/frpc -c /usr/local/frp/frpc.ini
autostart = true
startsecs = 10
autorestart = true
startretries = 100000
stdout_logfile = /usr/local/frp/frpc.log
----

. supervisord 服务管理
+
** linux
+
[,shell]
----
# 重启服务
systemctl restart supervisord
# 查看服务启动状态
systemctl status supervisord
# 配置 supervisord 开机自启
systemctl enable supervisord
----
** mac
+
用brew安装后，会自动生成服务文件 `/usr/local/Cellar/supervisor/4.2.4/homebrew.supervisor.service`
+
[,shell]
----
# 重启服务
brew services restart supervisor
# 查看服务启动状态
brew services info supervisor
----

. supervisor 进程管理（监听/启动/停止/重启）
+
[,shell]
----
# 查看所有进程的状态
supervisorctl status
# 停止 frpc
supervisorctl stop frpc
# 启动 frpc
supervisorctl start frpc
# 重启 frpc
supervisorctl restart frpc
# 配置文件修改后可以使用该命令加载新的配置
supervisorctl update
# 重新启动配置中的所有程序
supervisorctl reload
----

== 使用
=== 访问服务端管理页面
http://x.x.x.x:7500

=== 访问客户端管理页面
http://x.x.x.x:7400

=== ssh访问客户端
[,shell]
----
ssh -oPort=6000 root@x.x.x.x
----
[NOTE]
====
服务器防火墙一定要打开6000端口给用户从互联网访问
====
