= frp
:sectnums:
:scripts: cjk
:toc:
:toc-title: 目录
:toclevels: 2
:doctype: book
:experimental:

== frp 简介
=== 文档
https://gofrp.org/docs/overview/

=== frp 是什么？
frp 是一个专注于内网穿透的高性能的反向代理应用，支持 TCP、UDP、HTTP、HTTPS 等多种协议。可以将内网服务以安全、便捷的方式通过具有公网 IP 节点的中转暴露到公网。

=== 为什么使用 frp？
通过在具有公网 IP 的节点上部署 frp 服务端，可以轻松地将内网服务穿透到公网，同时提供诸多专业的功能特性，这包括：

. 客户端服务端通信支持 TCP、KCP 以及 Websocket 等多种协议。
. 采用 TCP 连接流式复用，在单个连接间承载更多请求，节省连接建立时间。
. 代理组间的负载均衡。
. 端口复用，多个服务通过同一个服务端端口暴露。
. 多个原生支持的客户端插件（静态文件查看，HTTP、SOCK5 代理等），便于独立使用 frp 客户端完成某些工作。
. 高度扩展性的服务端插件系统，方便结合自身需求进行功能扩展。
. 服务端和客户端 UI 页面。

== 下载
https://github.com/fatedier/frp/releases

== 解压
[,shell]
----
tar zxvf frp_0.48.1_linux_amd64.tar.gz
----

== 部署服务器
=== 上传
将解压后的以 `frps` 开头的系列文件上传到具有公网 IP 的机器上，建议放置到 `/usr/local/frp/` 目录中

=== 配置
./usr/local/frp/frps.yml
[source,yml]
----
auth:
  # 客户端连上来需要用到的令牌
  token: xxxxxxxx

# 服务器监听端口(须保证打通防火墙，从互联网可以访问这个端口)
bindPort: 40070

# 下面三种udp传输类型同时只能启用一个
# xtcp用来打洞的监听端口(xtcp 绑定的是 udp 端口，可以和 bindPort 一样)
# bindUdpPort: 45700
# 服务器启用kcp(kcp 绑定的是 udp 端口，可以和 bindPort 一样)
# kcpBindPort: 45700
# 服务器启用quic(quic 绑定的是 udp 端口，可以和 bindPort 一样)
quicBindPort: 40070

# 自定义TLS加密(除了xtcp，否则与use_encryption加密重复了)
transport:
  tls:
    # 服务端检验签名是否正确的CA证书(为减少麻烦且适合使用场景，由服务端统一生成)
    trustedCaFile: /usr/local/frp/ca.crt
    # 服务端发送数据签名使用的密钥(为减少麻烦且适合使用场景，由服务端统一生成)
    certFile: /usr/local/frp/server.crt
    keyFile: /usr/local/frp/server.key

# 服务端管理界面
# 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
webServer:
  addr: 0.0.0.0
  port: 40075
  # dashboard 用户名密码，可选，默认为空
  user: admin
  password: xxxxxxxx
  # 通过配置 TLS 证书来启用 HTTPS
  tls:
    certFile: /usr/local/frp/server.crt
    keyFile: /usr/local/frp/server.key
----

=== 运行
==== 直接运行
[,shell]
----
./frps -c ./frps.yml
----

==== 后台运行
[,shell]
----
mkdir -p /var/log/frp
nohup /usr/local/frp/frps -c /usr/local/frp/frps.yml > /usr/local/frp/frps.log 2>&1 &
----

==== systemd方式
./etc/systemd/system/frps.service
[,ini]
----
[Unit]
# 服务名称，可自定义
Description = frp server
After = network.target syslog.target
Wants = network.target

[Service]
Type = simple
# 启动frps的命令，需修改为您的frps的安装路径
ExecStart = /usr/local/frp/frps -c /usr/local/frp/frps.yml

[Install]
WantedBy = multi-user.target
----

[,shell]
----
# 启动服务
systemctl start frps
# 停止服务
systemctl stop frps
# 重启服务
systemctl restart frps
# 查看服务状态
systemctl status frps
# 配置 frps 开机自启
systemctl enable frps
----

==== Supervisor方式
./etc/supervisord.conf
[,ini]
----
....

[include]
files = supervisord.d/*.ini
----

./etc/supervisord.d/frps.ini
[,ini]
----
[program:frps]
directory = /usr/local/frp/
command = /usr/local/frp/frps -c /usr/local/frp/frps.yml
autostart = true
startsecs = 10
autorestart = true
startretries = 100000
stdout_logfile = /usr/local/frp/frps.log
----

* supervisord 服务管理
[,shell]
----
# 重启服务
systemctl restart supervisord
# 查看服务启动状态
systemctl status supervisord
# 配置 supervisord 开机自启
systemctl enable supervisord
----

* supervisor 进程管理（监听/启动/停止/重启）
[,shell]
----
# 查看所有进程的状态
supervisorctl status
# 停止 frps
supervisorctl stop frps
# 启动 frps
supervisorctl start frps
# 重启 frps
supervisorctl restart frps
# 配置文件修改后可以使用该命令加载新的配置
supervisorctl update
# 重新启动配置中的所有程序
supervisorctl reload
----

== 部署客户端
=== 上传
将解压后的以 `frpc` 开头的系列文件上传到内网服务所在的机器上，建议放置到 `/usr/local/frp/` 目录中

=== 配置
./usr/local/frp/frpc.yml
[source,yml]
----
auth:
  # 客户端连接服务器需要用到的令牌
  token: AHiJDS2Q5hmO2G4XkTIl3khjuDPls6lVbVoU9n2lYDE4VIcsVs0P2bzErBKMcWrs

# 客户端访问服务器的地址
serverAddr: <服务端外网地址>
# 客户端访问服务器的端口
serverPort: 40070


# 客户端与服务端之间的传输协议
transport:
  # 以下的kcp/quic只能同时启用一个，而且当只有两个都禁用时，才能使用xtcp
  # 启用 kcp 协议(上面的serverPort 必须指定为 frps 的 kcpBindPort)
  # protocol: "kcp"
  # 启用 QUIC 协议(上面的serverPort 必须指定为 frps 的 quicBindPort)
  # protocol: "quic"
  tls:
    # 客户端校验签名是否正确信任(为减少麻烦且适合使用场景，由服务端统一生成)
    trustedCaFile: /usr/local/frp/ca.crt
    # 客户端发送数据签名使用的密钥(为减少麻烦且适合使用场景，由服务端统一生成)
    certFile: /usr/local/frp/client.crt
    keyFile: /usr/local/frp/client.key

# 客户端管理界面
webServer:
  addr: 127.0.0.1
  port: 40175
  user: admin
  password: xxxxxxxx
  # 通过配置 TLS 证书来启用 HTTPS
  tls:
    certFile: /usr/local/frp/client.crt
    keyFile: /usr/local/frp/client.key

proxies:
  # 将客户端ssh暴露到外网
  - name: gateway01-ssh
    type: tcp
    localIP: 127.0.0.1
    # 客户端本地开启ssh的端口号
    localPort: 10000
    # 表示在 frps 服务端监听的端口，访问此端口的流量将被转发到本地服务的相应端口
    remotePort: 40170
    transport:
      # 启用加密
      useEncryption: true
      # 启用压缩
      useCompression: true

  - name: gateway01-admin-ui
    type: tcp
    localIP: 127.0.0.1
    # 表示在 frps 服务端监听的端口，访问此端口的流量将被转发到本地服务的相应端口
    localPort: 40175
    remotePort: 40175
    transport:
      # 启用加密
      useEncryption: true
      # 启用压缩
      useCompression: true
----

=== 运行
==== 直接运行
[,shell]
----
./frpc -c ./frpc.yml
----

==== 后台运行
[,shell]
----
mkdir -p /var/log/frp
nohup /usr/local/frp/frpc -c /usr/local/frp/frpc.yml > /usr/local/frp/frpc.log 2>&1 &
----

==== systemd方式
./etc/systemd/system/frpc.service
[,ini]
----
[Unit]
# 服务名称，可自定义
Description = frp client
After = network.target syslog.target
Wants = network.target

[Service]
Type = simple
# 启动frpc的命令，需修改为您的frpc的安装路径
ExecStart = /usr/local/frp/frpc -c /usr/local/frp/frpc.yml

[Install]
WantedBy = multi-user.target
----
[,shell]
----
# 启动服务
systemctl start frpc
# 停止服务
systemctl stop frpc
# 重启服务
systemctl restart frpc
# 查看服务状态
systemctl status frpc
# 配置 frpc 开机自启
systemctl enable frpc
----

==== Supervisor方式
. 查看默认的配置文件 supervisord.conf
** linux
+
./etc/supervisord.conf
[,ini]
----
....

[include]
files = supervisord.d/*.ini
----

** mac
+
./usr/local/etc/supervisord.conf
[,ini]
----
....

[include]
files = /usr/local/etc/supervisor.d/*.ini
----

. 编辑进程的配置文件
+
** linux->/etc/supervisord.d/frpc.ini
** mac->/usr/local/etc/supervisor.d/frpc.ini
+
[,ini]
----
[program:frpc]
directory = /root/
command = /usr/local/frp/frpc -c /usr/local/frp/frpc.yml
autostart = true
startsecs = 10
autorestart = true
startretries = 100000
stdout_logfile = /usr/local/frp/frpc.log
----

. supervisord 服务管理
+
** linux
+
[,shell]
----
# 重启服务
systemctl restart supervisord
# 查看服务启动状态
systemctl status supervisord
# 配置 supervisord 开机自启
systemctl enable supervisord
----
** mac
+
用brew安装后，会自动生成服务文件 `/usr/local/Cellar/supervisor/4.2.4/homebrew.supervisor.service`
+
[,shell]
----
# 重启服务
brew services restart supervisor
# 查看服务启动状态
brew services info supervisor
----

. supervisor 进程管理（监听/启动/停止/重启）
+
[,shell]
----
# 查看所有进程的状态
supervisorctl status
# 停止 frpc
supervisorctl stop frpc
# 启动 frpc
supervisorctl start frpc
# 重启 frpc
supervisorctl restart frpc
# 配置文件修改后可以使用该命令加载新的配置
supervisorctl update
# 重新启动配置中的所有程序
supervisorctl reload
----

== 使用
=== 访问服务端管理页面
http://x.x.x.x:40075

=== 访问客户端管理页面
http://x.x.x.x:40175

=== ssh访问客户端
[,shell]
----
ssh -oPort=40170 root@x.x.x.x
----
[NOTE]
====
服务器防火墙一定要打开6000端口给用户从互联网访问
====

== 附录
=== OpenSSL 生成证书示例
==== 准备默认 OpenSSL 配置文件于当前目录
[shell,bash]
----
cd /usr/local/frp/
cp /etc/pki/tls/openssl.cnf ./my-openssl.cnf
----
如果不存在可以使用下面的命令来创建
[shell,bash]
----
cat > my-openssl.cnf << EOF
[ ca ]
default_ca = CA_default
[ CA_default ]
x509_extensions = usr_cert
[ req ]
default_bits        = 2048
default_md          = sha256
default_keyfile     = privkey.pem
distinguished_name  = req_distinguished_name
attributes          = req_attributes
x509_extensions     = v3_ca
string_mask         = utf8only
[ req_distinguished_name ]
[ req_attributes ]
[ usr_cert ]
basicConstraints       = CA:FALSE
nsComment              = "OpenSSL Generated Certificate"
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid,issuer
[ v3_ca ]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints       = CA:true
EOF
----

==== 生成默认 ca
[shell,bash]
----
# frps用下面的命令
openssl genrsa -out ca.key 2048
openssl req -x509 -new -nodes -key ca.key -subj "/CN=example.ca.com" -days 5000 -out ca.crt
----

==== 生成服务端证书
[shell,bash]
----
openssl genrsa -out server.key 2048

openssl req -new -sha256 -key server.key \
    -subj "/C=XX/ST=DEFAULT/L=DEFAULT/O=DEFAULT/CN=server.com" \
    -reqexts SAN \
    -config <(cat my-openssl.cnf <(printf "\n[SAN]\nsubjectAltName=DNS:localhost,IP:127.0.0.1,DNS:example.server.com")) \
    -out server.csr

openssl x509 -req -days 365 -sha256 \
	-in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
	-extfile <(printf "subjectAltName=DNS:localhost,IP:127.0.0.1,DNS:example.server.com") \
	-out server.crt
----

[NOTE]
====
请将 `127.0.0.1` 替换为公网的IP地址
====

==== 生成客户端的证书
[shell,bash]
----
openssl genrsa -out client.key 2048
openssl req -new -sha256 -key client.key \
    -subj "/C=XX/ST=DEFAULT/L=DEFAULT/O=DEFAULT/CN=client.com" \
    -reqexts SAN \
    -config <(cat my-openssl.cnf <(printf "\n[SAN]\nsubjectAltName=DNS:client.com,DNS:example.client.com")) \
    -out client.csr

openssl x509 -req -days 365 -sha256 \
    -in client.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
	-extfile <(printf "subjectAltName=DNS:client.com,DNS:example.client.com") \
	-out client.crt
----
