version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es
    environment:
      - discovery.type=single-node
      # - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    container_name: kibana
    # environment:
    #   - ELASTICSEARCH_URL=http://127.0.0.1:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge