version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    network_mode: bridge
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - es01
    links:
      - es01:elasticsearch
    network_mode: bridge
